### ISSUE TITLE
Upvoting count refresh error

### ISSUE THREAD

**Issue by pranavpunjabi** [PinkShirtBoys/ThinkTank#3]
While testing with two accounts on simultaneous basis, upvoting had a miscalculation.
In Debate **test2** Argument **Arg 1 Against Title**, I voted from first account (didn't refresh screen) and it reflected an increase from 0 to 1. 

While on a different machine, from the second account which was already open before the first account voting (voting still shows a count of 0), I upvoted again. The count went up from 0 to 1. 

When both machine screens are refreshed, contrary to expected behavior of two votes on each screen, each screen just shows one vote.

On checking with Parse, in class **Argument** for title **Arg 1 Against Title**, the **voters** array correctly stores the objectIds of the two users in consideration.

username1 : ppunjabi@purdue.edu
username2: pranavpunjabi@gmail.com

![image](https://cloud.githubusercontent.com/assets/5459674/11535925/18f362aa-98e4-11e5-8084-fad58520e718.png)

**Comment by rbarman** [comment]
That makes sense. The debate view is loaded with Parse data only at the start when the user goes to a Debate url. 

If you had refreshed before voting on the second machine, you would see the vote count at 2 and be able to up vote the argument to set it at 3. 

Possible fixes:
1. Transition to [Angular - Firebase](https://www.firebase.com/docs/web/libraries/angular/quickstart.html)
   - Firebase offers triple way binding so that changes in data are automatically updated  and persisted in all clients. 
   - [Parse does not offer this](http://stackoverflow.com/questions/23833773/is-it-possible-to-get-3-way-data-binding-in-an-angularjs-application-using-parse)
   - Downside of transitioning to firebase is that firebase is just a large JSON database that does not have well defined objects like Parse.com's `Session`, `Object`, etc
2. Load/refresh views from Parse every `n` seconds
   - Can be inefficient and waste API calls. 
3. Load the view from Parse once the up vote button is clicked and then increment `voteCount`
   - Easiest way, but the user will not visually see the increase in up votes from other people for an argument in real time; he would only see the increases only if he completely refresh the page

**Comment by rbarman** [comment]
Another possible fix is to use [react js](https://github.com/ParsePlatform/ParseReact) on top of our angular stack.
- React is just the view in an MVC stack
- [This library](https://github.com/ParsePlatform/ParseReact) is a layer on top of the parse js sdk that supposedly will let the react js views subscribe to Parse objects.
- Using react js for the View will ultimately be more scalable in a large scale application
